### ISSUE TITLE
Issue probably with Auth0

### ISSUE THREAD

**Issue by Oliv4945** [helium/console#1113]
Hi,

I am using the open source console,  self hosted. Authentication is made thanks to Auth0

When any user try to login the following is displayed in the console's log:
```
console_1   | 21:58:13.256 [info] GET /api/organizations/
console_1   | 21:58:13.442 [error] #PID<0.6040.0> running ConsoleWeb.Endpoint (connection #PID<0.6039.0>, stream id 1) terminated
console_1   | Server: phoenix_upstream:80 (http)
console_1   | Request: GET /api/organizations/
console_1   | ** (exit) an exception was raised:
console_1   |     ** (Poison.ParseError) unexpected token at position 0: N
console_1   |         (poison 5.0.0) lib/poison/parser.ex:164: Poison.Parser.parse!/2
console_1   |         (console 2.0.0) lib/console_web/plug/verify_access_token.ex:12: ConsoleWeb.AccessTokenDecoder.Auth0.decode_conn_access_token/1
console_1   |         (console 2.0.0) lib/console_web/plug/verify_access_token.ex:93: ConsoleWeb.Plug.VerifyAccessToken.call/2
console_1   |         (console 2.0.0) lib/console_web/auth_api_pipeline.ex:1: ConsoleWeb.AuthApiPipeline.plug_builder_call/2
console_1   |         (console 2.0.0) lib/console_web/router.ex:1: ConsoleWeb.Router.__pipe_through2__/1
console_1   |         (phoenix 1.6.5) lib/phoenix/router.ex:347: Phoenix.Router.__call__/2
console_1   |         (console 2.0.0) lib/console_web/endpoint.ex:1: ConsoleWeb.Endpoint.plug_builder_call/2
console_1   |         (console 2.0.0) lib/console_web/endpoint.ex:1: ConsoleWeb.Endpoint.call/2
```

The browser indicates:
![image](https://user-images.githubusercontent.com/6248122/162762635-cc4238ce-c0cf-416a-bea2-2aa480ea78f9.png)

The error 500 is from the server, but what about the content security policy? Can it be related?  
Is there a way to increase console verbosity to get the full offending message and not just the character `N` ?

Also do you have any advice related to Auth0 configuration? 

Last question: can we use MagicLink as a workaround and easily switch back to Auth0 when this issue will be solved?

.env file:
```
# Core env vars
SECRET_KEY_BASE=n<REDACTED>g==
CLOAK_SECRET_KEY=r<REDACTED>0=
GUARDIAN_SECRET_KEY=b<REDACTED>Q==
ROUTER_SECRETS=1649346696:x<REDACTED>g==
ENV_DOMAIN=hlm.loraclouddemo.com
SOCKET_CHECK_ORIGIN=https://h<REDACTED>g.com
DATABASE_DB=console
DATABASE_HOST=postgres
DATABASE_USER=postgres
DATABASE_PASSWORD=r<REDACTED>L
DATABASE_POOL_SIZE=20
BLOCKCHAIN_API_RETRY=1
OUI=24
SELF_HOSTED=true

# If using Auth0 to authenticate users, fill in these variables
AUTH_0_CLIENT_ID=G<REDACTED>h
AUTH_0_DOMAIN=<REDACTED>g.eu.auth0.com
AUTH0_BASE_URL=https://<REDACTED>g.eu.auth0.com/

# If using Magic to authenticate users, fill in these variables
USE_MAGIC_AUTH=false
MAGIC_PUBLIC_KEY=[Publishable Api Key in Magic dashboard]
MAGIC_SECRET_KEY=[Secret Key in Magic dashboard]

# Mailgun
# MAILGUN_API_KEY=[Your Mailgun api key (optional)]
# SITE_DOMAIN_MAILGUN=[Your Mailgun host domain (optional)]
# MAILGUN_URL=[https://api.eu.mailgun.net/v3 if using an EU server. Remove setting to use US servers.]
# MAIL_FROM=[Helium <console@example.com> (optional)]
# MAIL_REPLY_TO=[console@example.com (optional)]

# Mapbox
MAPBOX_PRIVATE_KEY=p<REDACTED>w
MAPBOX_STYLE_URL=mapbox://styles/mapbox/light-v10

# Settings that are up to you
INITIAL_ORG_GIFTED_DC=10000
DISABLE_USER_BURN=false
USER_INVITE_ONLY=false
MAX_DEVICES_IN_ORG=10000
```

.env-router file:
```
# Default Helium's seed nodes
ROUTER_SEED_NODES=/ip4/18.217.27.26/tcp/2154,/ip4/35.161.222.43/tcp/443,/ip4/99.80.158.114/tcp/2154

# OUI used by router (see https://developer.helium.com/blockchain/blockchain-cli#oui)
ROUTER_OUI=24

# State Channel Open amount
ROUTER_SC_OPEN_DC_AMOUNT=2000

# State Channel block expiration
# FYI: There is a cost to open a state channel (about 35k DC)
# Current min: 15 blocks, max abbout 5000 blocks
ROUTER_SC_EXPIRATION_INTERVAL=1000

# State Channel Expiration Buffer
# Minimum distance state channels can expire within another expiration
# default: 15 when not set
ROUTER_SC_EXPIRATION_BUFFER=15

# Console's connection info (see https://github.com/helium/console)
ROUTER_CONSOLE_ENDPOINT=http://helium_console:4000
ROUTER_CONSOLE_WS_ENDPOINT=ws://helium_console:4000/socket/router/websocket
# Public facing endpoint to POST downlinks for devices
ROUTER_CONSOLE_DOWNLINK_ENDPOINT=https://h<REDACTED>.com
ROUTER_CONSOLE_SECRET=<REDACTED>:x<REDACTED>g==

# Max time to wait for uplinks in ms
ROUTER_FRAME_TIMEOUT=500

# Turn on/off xor filter worker (anything else than true is off, disabled by default)
ROUTER_XOR_FILTER_WORKER=false

# Turn on/off HTTP integration url checks like DNS, IP... (anything else than false is on, enabled by default)
ROUTER_HTTP_CHANNEL_URL_CHECK=true

# Set max number fo downlink allowed to be queued for one device (Defaults to 20).
ROUTER_DEVICE_QUEUE_SIZE_LIMIT=20
```

**Comment by vicmgs** [comment]
hi, please remove the trailing slash in the AUTH0_BASE_URL

**Comment by vicmgs** [comment]
As for your configuration in Auth0, create a new application for Single Page Application.

Under settings tab, for Allowed Callback URLs, Allowed Logout URLs, Allowed Web Origins, Allowed Origins (CORS), put your full site url (ex. https://staging-console.helium.wtf)

**Comment by jdgemm** [comment]
@Oliv4945 what's the reason you're choosing to use auth0 vs magic link? The team fully supports magic link with each release, and hasn't used auth0 for many months.

**Comment by Oliv4945** [comment]
Thanks @vicmgs we also figured out in parallel that [this line](https://github.com/helium/console/blob/master/lib/console_web/plug/verify_access_token.ex#L11) is unconditionally adding it. Should I propose a PR to add a comment in the  `.env` template, or you want to handle it differently?

@jdgemm : because we are already using Auth0 for other projects so it avoids creating another vendor account, and we were not aware that the Auth0 is not tested by Nova anymore.

**Comment by vicmgs** [comment]
I have added the comment to the .env template, thank you

**Comment by Oliv4945** [comment]
@vicmgs thanks, so if I understand it correctly you plan to deprecate Auth0?

**Comment by vicmgs** [comment]
@Oliv4945 that is up to @jdgemm. We are still debating the situation.

**Comment by Oliv4945** [comment]
Ok, I am closing this issue, thanks for your help. 
Also I am not partial because I already have Auth0 setup in my company but providing some choice instead of vendor lock in is always good, especially as you already develop both interfaces.
