### ISSUE TITLE
Unable to accept an invitation

### ISSUE THREAD

**Issue by Oliv4945** [helium/console#1121]
Hi,

I am using my open source self hosted console, v2.2.6 with Auth0 authentication.  
User can create accounts, log in and create their own organizations but we can't invite anyone to an organization, either a completely new user or an existing one.

**First kind of error**

<details>
<summary>Click to expand browser logs</summary>

```
TypeError: this.props.user is undefined
    render webpack:///./js/app.js_+_501_modules?:5710
    React 7
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 6
    componentDidUpdate webpack:///./js/app.js_+_501_modules?:5681
    promise callback*componentDidUpdate webpack:///./js/app.js_+_501_modules?:5681
    React 2
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 4
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 5
    initAuth0 webpack:///./js/app.js_+_501_modules?:3158
    Auth0Provider webpack:///./js/app.js_+_501_modules?:3161
    React 2
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 3
    X webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:18
    onmessage webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:15
    EventHandlerNonNull* webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:14
    60053 https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> webpack:///./node_modules/scheduler/index.js?:4
    63840 https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> React
    64448 Redux
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> React
    73935 Redux
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> webpack:///./js/app.js_+_501_modules?:7
    17857 https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    O https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    r https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
react-dom.production.min.js:210:195
Uncaught (in promise) TypeError: this.props.user is undefined
    render webpack:///./js/app.js_+_501_modules?:5710
    React 7
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 6
    componentDidUpdate webpack:///./js/app.js_+_501_modules?:5681
    promise callback*componentDidUpdate webpack:///./js/app.js_+_501_modules?:5681
    React 2
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 4
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 5
    initAuth0 webpack:///./js/app.js_+_501_modules?:3158
    Auth0Provider webpack:///./js/app.js_+_501_modules?:3161
    React 2
    unstable_runWithPriority webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:20
    React 3
    X webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:18
    onmessage webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:15
    EventHandlerNonNull* webpack:///./node_modules/scheduler/cjs/scheduler.production.min.js?:14
    60053 https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> webpack:///./node_modules/scheduler/index.js?:4
    63840 https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> React
    64448 Redux
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> React
    73935 Redux
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> webpack:///./js/app.js_+_501_modules?:7
    17857 https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    o https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    O https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/main.bundle-ae0306f8874352386e45de0d945bedc5.js?vsn=d:1
    r https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
    <anonymous> https://domain.com/js/runtime.bundle-ed8e18f5fde80027df1795d655d30442.js?vsn=d:1
```
</details>

<details>
<summary>Click to expand console logs</summary>

```
console_1   | 16:33:50.914 [info] GET /api/router/devices/unknown
console_1   | 16:33:50.917 [info] Sent 200 in 2ms
console_1   | 16:33:57.046 [info] GET /invitations/accept/2OVdynHGr_jXCsdpE0PMTFvXvpKhEaji2Y5Kwlc8IobT5wD-iWWd6nbUzHplLG-2
console_1   | 16:33:57.047 [info] Sent 302 in 1ms
console_1   | 16:33:57.130 [info] GET /join_organization
console_1   | 16:33:57.130 [info] Sent 200 in 375µs
console_1   | 16:33:57.234 [info] CONNECTED TO ConsoleWeb.UserSocket in 3ms
console_1   |   Transport: :websocket
console_1   |   Serializer: Phoenix.Socket.V2.JSONSerializer
console_1   |   Parameters: %{"organization_id" => "93959f79-ab4b-49c4-ac88-3ea5e5aad36b", "token" => "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik16QTBSRE5DTlRoRE5EUTNNRGcxUmpsQlJFTXhSRVEyTVVZeU16YzNOMFZHTlRNNE5FWkRRZyJ9.eyJuaWNrbmFtZSI6Im9naW1lbmV6IiwibmFtZSI6Im9naW1lbmV6QHNlbXRlY2guY29tIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzdjNzE4OWY5ZmI0OTdjZWE0OWQ3NWY1YmQzMTQ5OWIwP3M9NDgwJnI9cGcmZD1odHRwcyUzQSUyRiUyRmNkbi5hdXRoMC5jb20lMkZhdmF0YXJzJTJGb2cucG5nIiwidXBkYXRlZF9hdCI6IjIwMjItMDQtMTJUMDk6NDg6NDEuNDYyWiIsImVtYWlsIjoib2dpbWVuZXpAc2VtdGVjaC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9zZW10ZWNoLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZDFjYmQ4OGVkZTAwYTBjZGZhODM4ZDIiLCJhdWQiOiJHcU5vQnhkMGxVN2xDNGJyQlRHRzhlWHJZaWRHZWNraCIsImlhdCI6MTY0OTg2NzMwMCwiZXhwIjoxNjQ5OTAzMzAwLCJub25jZSI6IlQwUTJjMDVVZHpoVlVGTjBSWEkxT0RSNFRWcHhhVVpqV0RWclNFZFNNV2xKVjJKTk1YVjBhM0pvY2c9PSJ9.ln-JsGY7G8FGHqonZ6vF76a7rmi2IRVMXH1NGfNL3EP_qUdf0UVaenlxhzHQXUBVkbR-UjIgBNTjY0nxzxKUGubPowk925Qps-88sGjYT1TdZiXbQnV7ZNAqqZH-poVqbIvkzrCUC7vJIeLWA7T7Ea7pv_gYp2K979viPM0w8au1XhMLp3AdwilWLCg6sHq30hkttzr-KpxdPqnIuxyPMICEUMCODV-eSmak1tGX9C3XkxAtDszG47skyNg2YYAg-7rR42vTFCBOns8gNidzsOiBoEkDFzj5UQEj_74_h2E7wxVkojDMg2nwErvbaIkRouTjUhvGDWysyrK3-976zw", "vsn" => "2.0.0"}
console_1   | 16:34:02.345 [info] GET /api/invitations/2OVdynHGr_jXCsdpE0PMTFvXvpKhEaji2Y5Kwlc8IobT5wD-iWWd6nbUzHplLG-2
console_1   | 16:34:02.348 [info] Sent 200 in 2ms
console_1   | 16:34:02.355 [info] GET /api/organizations/
console_1   | 16:34:02.359 [info] Sent 200 in 4ms
```
</details>

**Second type of error:**

<details>
<summary>Click to expand browser logs</summary>

```
TypeError: Cannot read properties of undefined (reading 'sub')
at JoinOrganizationPrompt.render (app.js_+_501_modules:5710:35)
at gi (react-dom.production.min.js:183:192)
at fi (react-dom.production.min.js:182:224)
at Rj (react-dom.production.min.js:264:490)
at Qj (react-dom.production.min.js:247:265)
at Kj (react-dom.production.min.js:247:194)
at yj (react-dom.production.min.js:240:172)
at eval (react-dom.production.min.js:124:115)
at exports.unstable_runWithPriority (scheduler.production.min.js:20:467)
at cg (react-dom.production.min.js:123:325)
Ci @ react-dom.production.min.js:210
Xi.c.callback @ react-dom.production.min.js:227
Cg @ react-dom.production.min.js:132
Ji @ react-dom.production.min.js:213
Sj @ react-dom.production.min.js:256
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
Jj @ react-dom.production.min.js:249
yj @ react-dom.production.min.js:240
eval @ react-dom.production.min.js:124
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
fg @ react-dom.production.min.js:124
gg @ react-dom.production.min.js:123
Ig @ react-dom.production.min.js:231
enqueueSetState @ react-dom.production.min.js:133
F.setState @ react.production.min.js:12
eval @ app.js_+_501_modules:5681
Promise.then (async)
componentDidUpdate @ app.js_+_501_modules:5681
Ji @ react-dom.production.min.js:213
Sj @ react-dom.production.min.js:256
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
Jj @ react-dom.production.min.js:249
yj @ react-dom.production.min.js:240
eval @ react-dom.production.min.js:124
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
fg @ react-dom.production.min.js:124
gg @ react-dom.production.min.js:123
Ig @ react-dom.production.min.js:231
zh @ react-dom.production.min.js:164
initAuth0 @ app.js_+_501_modules:3158
await in initAuth0 (async)
eval @ app.js_+_501_modules:3161
Ii @ react-dom.production.min.js:212
Vj @ react-dom.production.min.js:258
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
Dj @ react-dom.production.min.js:258
eval @ react-dom.production.min.js:257
X @ scheduler.production.min.js:18
H.port1.onmessage @ scheduler.production.min.js:15
app.js_+_501_modules:5710 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sub')
at JoinOrganizationPrompt.render (app.js_+_501_modules:5710:35)
at gi (react-dom.production.min.js:183:192)
at fi (react-dom.production.min.js:182:224)
at Rj (react-dom.production.min.js:264:490)
at Qj (react-dom.production.min.js:247:265)
at Kj (react-dom.production.min.js:247:194)
at yj (react-dom.production.min.js:240:172)
at eval (react-dom.production.min.js:124:115)
at exports.unstable_runWithPriority (scheduler.production.min.js:20:467)
at cg (react-dom.production.min.js:123:325)
render @ app.js_+_501_modules:5710
gi @ react-dom.production.min.js:183
fi @ react-dom.production.min.js:182
Rj @ react-dom.production.min.js:264
Qj @ react-dom.production.min.js:247
Kj @ react-dom.production.min.js:247
yj @ react-dom.production.min.js:240
eval @ react-dom.production.min.js:124
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
fg @ react-dom.production.min.js:124
gg @ react-dom.production.min.js:123
Ig @ react-dom.production.min.js:231
enqueueSetState @ react-dom.production.min.js:133
F.setState @ react.production.min.js:12
eval @ app.js_+_501_modules:5681
Promise.then (async)
componentDidUpdate @ app.js_+_501_modules:5681
Ji @ react-dom.production.min.js:213
Sj @ react-dom.production.min.js:256
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
Jj @ react-dom.production.min.js:249
yj @ react-dom.production.min.js:240
eval @ react-dom.production.min.js:124
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
fg @ react-dom.production.min.js:124
gg @ react-dom.production.min.js:123
Ig @ react-dom.production.min.js:231
zh @ react-dom.production.min.js:164
initAuth0 @ app.js_+_501_modules:3158
await in initAuth0 (async)
eval @ app.js_+_501_modules:3161
Ii @ react-dom.production.min.js:212
Vj @ react-dom.production.min.js:258
exports.unstable_runWithPriority @ scheduler.production.min.js:20
cg @ react-dom.production.min.js:123
Dj @ react-dom.production.min.js:258
eval @ react-dom.production.min.js:257
X @ scheduler.production.min.js:18
H.port1.onmessage @ scheduler.production.min.js:15
```
</details>

<details>
<summary>Click to expand console logs</summary>

```
console_1   | 16:08:34.510 [info] GET /
console_1   | 16:08:34.511 [info] Sent 200 in 353µs
console_1   | 16:09:20.630 [info] GET /join_organization
console_1   | 16:09:20.630 [info] Sent 200 in 376µs
console_1   | 16:09:32.751 [info] GET /
console_1   | 16:09:32.752 [info] Sent 200 in 389µs
console_1   | 16:09:34.569 [info] GET /api/organizations/
console_1   | 16:09:34.573 [info] Sent 200 in 3ms
console_1   | 16:09:34.683 [info] GET /api/invitations/VQpZHPbtRyRyC90W5GjFTTc01NNN9G-cWng1ep68MZCrOE2Fh6_pdZnpMOHx80VV
console_1   | 16:09:34.685 [info] Sent 200 in 2ms
```
</details>

Thanks for you help

**Comment by ambuznego** [comment]
Hi @Oliv4945 thank you for reporting this. We've found the fix. Are you using the quay image by chance?

**Comment by Oliv4945** [comment]
@ambuznego yes, but I can also compile the console if it helps

**Comment by ambuznego** [comment]
@Oliv4945 I've merged the fix to `master`. Please feel free to pull that and upon the next release, switch back to quay image. Thank you so much!

**Comment by Oliv4945** [comment]
Hi, I confirm that it solved my issue, thanks for this quick fix!
