### ISSUE TITLE
Check origin change

### ISSUE THREAD

**Issue by disk91** [helium/console#461]
Since the new console update, I've got this error message
```
helium_console | 08:24:31.504 [error] Could not check origin for Phoenix.Socket transport.
helium_console | 
helium_console | Origin of the request: https://console.helium-iot.eu
helium_console | 
helium_console | This happens when you are attempting a socket connection to
helium_console | a different host than the one configured in your config/
helium_console | files. For example, in development the host is configured
helium_console | to "localhost" but you may be trying to access it from
helium_console | "127.0.0.1". To fix this issue, you may either:
helium_console | 
helium_console |   1. update [url: [host: ...]] to your actual host in the
helium_console |      config file for your current environment (recommended)
helium_console | 
helium_console |   2. pass the :check_origin option when configuring your
helium_console |      endpoint or when configuring the transport in your
helium_console |      UserSocket module, explicitly outlining which origins
helium_console |      are allowed:
helium_console | 
helium_console |         check_origin: ["https://example.com",
helium_console |                        "//another.com:888", "//other.com"]
helium_console | 
```

apparently the devices stopped to connect

I've applied the 2nd option proposed adding check origin ... and get console crash as a loop
```
helium_console | ERROR! Config provider Config.Reader failed with:
helium_console | ** (SyntaxError) _build/prod/rel/console/releases/0.0.1/releases.exs:15: syntax error before: cache_static_manifest
helium_console |     (elixir) src/elixir.erl:245: :elixir.eval/3
helium_console |     (elixir) lib/code.ex:240: Code.eval_string/3
helium_console |     (elixir) lib/config.ex:219: Config.__eval__!/2
helium_console |     (elixir) lib/config/reader.ex:44: Config.Reader.read!/2
helium_console |     (elixir) lib/config/reader.ex:24: Config.Reader.load/2
helium_console |     (elixir) lib/config/provider.ex:206: anonymous fn/2 in Config.Provider.run_providers/2
helium_console |     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
helium_console | 
helium_console | {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.SyntaxError',description=><<"syntax error before: cache_static_manifest">>,file=><<"/app/_build/prod/rel/console/releases/0.0.1/releases.exs">>,line=>15},[{elixir,eval,3,[{file,"src/elixir.erl"},{line,245}]},{'Elixir.Code',eval_string,3,[{file,"lib/code.ex"},{line,240}]},{'Elixir.Config','__eval__!',2,[{file,"lib/config.ex"},{line,219}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,44}]},{'Elixir.Config.Reader',load,2,[{file,"lib/config/reader.ex"},{line,24}]},{'Elixir.Config.Provider','-run_providers/2-fun-0-',2,[{file,"lib/config/provider.ex"},{line,206}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1948}]}]}}
helium_console | init terminating in do_boot ({,[{elixir,eval,3,[{_},{_}]},{Elixir.Code,eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,2,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]},{Elixir.Config.Reader,loa
```

**Comment by disk91** [comment]
sorry, I did not saw your previous response at the initial question as it was closed ticket.
