### ISSUE TITLE
RuntimeError: expected action/2 to return a Plug.Conn, all plugs must receive a connection

### ISSUE THREAD

**Issue by mfalkvidd** [helium/console#780]
1. Are you using Helium hosted Console or running your own open source Console?
My own open source, built from 6427c82bc4f8619b5bb3a5940099a8bdd6167a9e

Please describe your issue:
Every 10 minutes, the following is logged on my console (`docker logs helium_console -f`)
```
13:56:38.382 [error] #PID<0.5995.0> running ConsoleWeb.Endpoint (connection #PID<0.5993.0>, stream id 2) terminated
Server: console:4000 (http)
Request: POST /api/router/devices/update_in_xor_filter
** (exit) an exception was raised:
    ** (RuntimeError) expected action/2 to return a Plug.Conn, all plugs must receive a connection (conn) and return a connection, got: nil
        (console) lib/console_web/controllers/router/device_controller.ex:1: ConsoleWeb.Router.DeviceController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (console) lib/console_web/endpoint.ex:1: ConsoleWeb.Endpoint.plug_builder_call/2
        (console) lib/console_web/endpoint.ex:1: ConsoleWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /app/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
```

There doesn't seem to be any related info in the router log.

**Comment by vicmgs** [comment]
Found the bug, should be fixed next release
