### ISSUE TITLE
Error in console related to tzData_release

### ISSUE THREAD

**Issue by disk91** [helium/console#935]
1. Are you using Helium hosted Console or running your own open source Console?
OSS

```
helium_console | 22:41:50.296 [error] GenServer :tzdata_release_updater terminating
helium_console | ** (MatchError) no match of right hand side value: {:error, :timeout}
helium_console |     (tzdata) lib/tzdata/data_loader.ex:12: Tzdata.DataLoader.download_new/1
helium_console |     (tzdata) lib/tzdata/data_builder.ex:11: Tzdata.DataBuilder.load_and_save_table/0
helium_console |     (tzdata) lib/tzdata/release_updater.ex:48: Tzdata.ReleaseUpdater.poll_for_update/0
helium_console |     (tzdata) lib/tzdata/release_updater.ex:19: Tzdata.ReleaseUpdater.handle_info/2
helium_console |     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
helium_console |     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
helium_console |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
helium_console | Last message: :check_if_time_to_update

```

**Comment by vicmgs** [comment]
When is this happening
